/**
 * Created by leibo on 18/3/9.
 */
export default {
  admissionTicketHomePageObj: state => state.admissionTicketHomePageObj,
  nearList: state => state.nearList,
  themeTypeNameList: state => state.themeTypeNameList,
  adminNearTickeFilterObj: state => state.adminNearTickeFilterObj,
  hotList: state => state.hotList,
  outList: state => state.outList,
  cityList: state => state.cityList,
  outListObj: state => state.outListObj,
  featuredList: state => state.featuredList,
  hotCityList: state => state.hotCityList,
  cooperationList: state => state.cooperationList,
  topBigImageList: state => state.topBigImageList,
  bookKnowObj: state => state.bookKnowObj,
  pictureList: state => state.pictureList,
  ticketsDetailData: state => state.ticketsDetailData,
  transportMessage: state => state.transportMessage,
  ticketType_PriceMXList: state => state.ticketType_PriceMXList,
  ticketOrderDetail: state => state.ticketOrderDetail,
  admissionTicketMoreList: state => state.admissionTicketMoreList,
  regionClassificationList: state => state.regionClassificationList,
  themeList: state => state.themeList,
  seleteShowCtiyList: state => state.seleteShowCtiyList,
  seleteShowProvinceList: state => state.seleteShowProvinceList,
  ticketTourSiteImg: state => state.ticketTourSiteImg,
  ticketScenicSpot: state => state.ticketScenicSpot,
  searchThemeTypeList: state => state.searchThemeTypeList,
  ticketCommentDataList: state => state.ticketCommentDataList,
  allTicketCommendList: state => state.allTicketCommendList,
  getScoreTypeList: state => state.getScoreTypeList,
  numLength: state => state.numLength,
}
