export default {

  //loading
  isLoading: state => state.isLoading,
  user: state => state.user,
  text: state => state.text,
  //-----------首页-----------
  domesticDataList: state => state.domesticDataList,
  getTourSiteListImage: state => state.getTourSiteListImage,
  showQuit: state => state.showQuit,
  packMoneyObj: state => state.packMoneyObj,
  receivingAddressList: state => state.receivingAddressList,


  productDetailsObj: state => state.productDetailsObj,
  lineScheduleObj: state => state.lineScheduleObj,
  IncludeList: state => state.IncludeList,
  noWrapMoneyList: state => state.noWrapMoneyList,
  lineMenuList: state => state.lineMenuList,
  timesPriceList: state => state.timesPriceList,
  priceObj: state => state.priceObj,
  newPriceDetail: state => state.newPriceDetail,
  navList: state => state.navList,
  domesticGoodList: state => state.domesticGoodList,
  // pictureList: state => state.pictureList,

  aroundList: state => state.aroundList,
  shortLineList: state => state.shortLineList,
  longLineList: state => state.longLineList,
  payStr: state => state.payStr,
  myTourOrderList: state => state.myTourOrderList,
  orderDetail: state => state.orderDetail,
  collectionList: state => state.collectionList,
  commentMXObj: state => state.commentMXObj,
  commentData: state => state.commentData,
  newCommentData: state => state.newCommentData,
  jobList: state => state.jobList,
  educationList: state => state.educationList,
  getAreaInfoList: state => state.getAreaInfoList,
  showFixedComment: state => state.showFixedComment,
  useScoreDetailInfo: state => state.useScoreDetailInfo,
  userAllScoreList: state => state.userAllScoreList,
  topPageList: state => state.topPageList,
  hotAgenciesCityList: state => state.hotAgenciesCityList,
  outLongAreaList: state => state.outLongAreaList,
  outShortAreaList: state => state.outShortAreaList,
  contryAreaList: state => state.contryAreaList,
  nearAreaList: state => state.nearAreaList,
  nearAreaGoodList: state => state.nearAreaGoodList,
  shortLineGoodList: state => state.shortLineGoodList,
  longLineGoodList: state => state.longLineGoodList,

  //商户注册
  provinceDataList: state => state.provinceDataList,
  cityDataList: state => state.cityDataList,
  countyDataList: state => state.countyDataList,
  changeMineyTypeList: state => state.changeMineyTypeList,
  changeValueName: state => state.changeValueName,
  changeNameID: state => state.changeNameID,
  changeCompanyTypeList: state => state.changeCompanyTypeList,
  changeCompanyTypeValue: state => state.changeCompanyTypeValue,
  changeCompanyID: state => state.changeCompanyID,
  changeCooperationTypeList: state => state.changeCooperationTypeList,
  changeScopeOfOperationList: state => state.changeScopeOfOperationList,
  agenciesSearchCityList: state => state.agenciesSearchCityList,
  agenciesSearchTourSiteList: state => state.agenciesSearchTourSiteList,
  agenciesSearchGroupCityList: state => state.agenciesSearchGroupCityList,
  heelTourSearchMoreList: state => state.heelTourSearchMoreList,
  reasonList: state => state.reasonList,
  introList: state => state.introList,
  touristInfoList: state => state.touristInfoList,
  outCityName: state => state.outCityName,

  outCityObj: state => state.outCityObj,
  travelCommendList: state => state.travelCommendList,
  searchTravelObj: state => state.searchTravelObj,
}
